datasets:
  star: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /home/eric/temp/SeViLA-test/sevila_data/star/train.json
          storage: /home/eric/temp/SeViLA-test/sevila_data/star/train.json
        val:
          url: /home/eric/temp/SeViLA-test/sevila_data/star/val.json
          storage: /home/eric/temp/SeViLA-test/sevila_data/star/val.json
        test:
          url: /home/eric/temp/SeViLA-test/sevila_data/star/val.json
          storage: /home/eric/temp/SeViLA-test/sevila_data/star/val.json
      videos:
        storage: /home/eric/temp/SeViLA-test/dataset/Charades_v1_480