datasets:
  nextqa_cbl: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_train_flant5.json
          storage: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_train_flant5.json
        val:
          url: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_val_flant5.json
          storage: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_val_flant5.json
        test:
          url: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_val_flant5.json
          storage: /nas-ssd/shoubin/datasets/nextqa/caption-based-localization/ft_val_flant5.json
      videos:
        storage: /nas-hdd/shoubin/vidor/videos/